### ISSUE TITLE
libpython-clj using simpletransformers sometimes hanging

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#93] opened 2020-04-08 13:30 UTC
As a continuation of the discussion at the end of #43 

Please find here https://github.com/behrica/test-simple-transformers-clj.git

a reproducible example (including Dockerfile and clojure code)
which "fails" some times and "works sometimes".

It is a clojure + libpython-clj version of the simpletransformers minimal start for text classification, as seen here:
https://github.com/ThilinaRajapakse/simpletransformers#minimal-start-for-binary-classification

The Dockerfile here: https://github.com/behrica/test-simple-transformers-clj/blob/master/Dockerfile
creates a docker image with clojure, anaconda, simpletransformers python library and  libpython-clj

The "docker run" runs then this clojure file here (via lein exec)
https://github.com/behrica/test-simple-transformers-clj/blob/master/src/test_simple_transformers_clj/core.clj

This run "hangs" most of the time on the line:
```
(py. model train_model train-df)
```
but not always.

Running a "lein repl" inside the container and copy/paste the same code **does work**
mostly...

I see one very strange difference between running the code via  docker run (=  "lein exec" ) and "inside repl":
The "lein exec" way does not show any python logging.... while in the repl it does.

In my experiments I noticed as well that the clojure printing to stdout and python logging are "out of sync".

So having (println ...) around "(py.   model train_model train-df)"   shows first both clojure println and then the python logging (or they are intermixed). Maybe related to flushing of the python logs

**Comment by cnuernber** [comment] 2020-04-08 13:54
Interesting issue.  

One thing to try would be turn off io redirection, this can be done in the initialize step.

I wonder if python logging is doing something clever to bypass python stdout/stderr.  They could, for instance, get the actual file handle and write directly to it thus bypassing sys.stdout.  

In any case, I think that would cause the output issues but it shouldn't affect the hanging issues.

**Comment by behrica** [comment] 2020-04-08 14:13
Currently 8 / 10 container runs hang.

I will disable io redirection and see if it changes.

**Comment by behrica** [comment] 2020-04-08 14:24
Disable the io redirect makes the python logging appear in the "lein exec" calls.

**Comment by behrica** [comment] 2020-04-08 14:36
But the percentage of hanging is the same: 8/10

**Comment by behrica** [comment] 2020-04-08 15:03
Surrounding the whole code with 
(py/with-gil-stack-rc-context

)

solves it.

10/10 containers finish with this change.

**Comment by cnuernber** [comment] 2020-04-08 15:06
It is unfortunate that is necessary but it is right now I believe.  That is the recommendation in our document about stack and gc scope; for production use cases use python from one and only one thread and surround all access with the scoping mechanism.  Not all C libraries from python are OK with being accessed from multiple threads regardless of if you serialize that access.

I feel like there is something fixable there but the time required to really nail it down currently appears a bit too much.

**Comment by behrica** [comment] 2020-04-08 15:20
Fine, I saw the documentation.

What is unclear to me is, why you say that this is important for access from multiple threads (only ?)
My code does not use multiple threads..., does it ? Maybe via the gc ???

So "why" do i need to use in my case here: https://github.com/behrica/test-simple-transformers-clj/blob/master/src/test_simple_transformers_clj/core.clj
the with-gil-stack-rc-context ?

It seems "very easy" clojure code. 5 lines....

For a user of libpython-clj it is not clear, under which circumstances the wrapping inside  "with-gil-stack-rc-context" is required,
(and that there is maybe a difference between "in repl" and "outside repl" ...)

Maybe the answer is "eventually always, depending on the python library being called".
But then we should maybe document this more prominently, even on the "quick start" page.

**Comment by cnuernber** [comment] 2020-04-08 15:31
Carsten, if I knew the exact answer to what you are asking I would just implement the fix and we would all go on with our lives :-).  The java GC now just marks things that are out of scope but the actual cleanup-hanging-references call happens when the gil context cleans up:

https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj/python/interpreter.clj#L351

If you don't use a gc-context like what you have above, then this call happens on every python access.  So every python function call you are grabbing the gil, doing your thing, and then releasing the gil and clearing the gc reference pool.  In most of these cases the actual system gc hasn't run so there shouldn't be anything in the pool.  

Even when we disabled releasing reference entirely we still were getting issues with specifically torch but also other libraries.  So somewhere in the fine-grained GIL acquire/release pathways and the reference mechanism combined with who-knows-what C libraries under the covers there is a pathway for hanging or outright crashing.  

> Maybe the answer is "eventually always, depending on the python library being called".
> But then we should maybe document this more prominently, even on the "quick start" page.

Yes, this does make sense and perhaps we should elevate this type of thing.

**Comment by behrica** [comment] 2020-04-08 15:32
I read the text here in detail:
https://github.com/clj-python/libpython-clj/blob/master/docs/scopes-and-gc.md

and the current wording seems to suggest that the usage of "with-gil-stack-rc-context" is needed for "advanced" usage or very "specific situations".

As we saw, the following very simple code hangs in 8 / 10 cases, and it is very hard to discover why,
so I would propose to add something do the "beginner documentation".

If not we risk that a lot of users , give up with your very nice library quickly....

```
 (def train-data  [["Example sentence belonging to class 1"  1]
                    ["Example sentence belonging to class 0"  0]])
  (def eval-data [["Example eval sentence belonging to class 1"  1]
                  ["Example eval sentence belonging to class 0" 0]])
  (def eval-df  (pd/DataFrame eval-data))
  (def train-df  (pd/DataFrame train-data))
  (def model (ClassificationModel "roberta"  "roberta-base" :use_cuda false
                                  :args {:overwrite_output_dir true} ))
  (py. model train_model train-df)
```

**Comment by behrica** [comment] 2020-04-08 15:33
I will as well clean up my code here : https://github.com/behrica/test-simple-transformers-clj and maybe you can link to it as a example.

**Comment by cnuernber** [comment] 2020-04-08 15:36
OK, thanks that helps a lot.  I will update the gc/scope documentation to make the wording stronger and include some text about this issue on the README so it is visible from the very start.

**Comment by behrica** [comment] 2020-04-08 16:03
Hmmmm. I have the hanging again...
After the "cleaning" of the code... in which I removed the (println) lines)

**Comment by cnuernber** [comment] 2020-04-08 16:11
This is in the docker container but you don't see this behavior in your repl?

**Comment by behrica** [comment] 2020-04-08 17:02
I am currently only trying the "docker run" to have something repeatable.

I have as well the impression that it might depend on:
- using "docker run"  vs "rocker -ti run"  vs "docker run -d "

I noticed that transformers is using the tqdm library for progress report,
which does funny stuff with the tty.
Maybe this interacts somehow with the python logging and clojure output.
(and this is different, if there is a tty or not ...)

**Comment by behrica** [comment] 2020-04-08 17:19
Is there a way to do this any of this in libpython-clj:
https://stackoverflow.com/questions/6735917/redirecting-stdout-to-nothing-in-python

To disable python output completely ?

**Comment by cnuernber** [comment] 2020-04-08 17:27
You could do what the article suggest directly.
Something like:
`(py/set-attr (get/load-module "sys") "stdout" nil)`

**Comment by behrica** [comment] 2020-04-08 21:24
I found tow options in simpletransformers to disable multi-core.
That seems to fix it...

```
(def model (ClassificationModel "roberta"  "roberta-base" :use_cuda false                                                                                                                                                                  
                                  :args {:overwrite_output_dir true                                                                                                                                                                          
                                         :process_count 1                                                                                                                                                                                    
                                         :use_multiprocessing false                                                                                                                                                                          
                                         } ))                      
```

**Comment by behrica** [comment] 2020-04-08 21:53
Without multi processing , the with-gil-stack-rc-context is not needed, it seems.

I did 20 runs, and all passed.

So somehow libpython-clj has difficulties with code like:

```
if use_multiprocessing:
            with Pool(process_count) as p:
                features = list(
                    tqdm(
                        p.imap(convert_example_to_feature_sliding_window, examples, chunksize=500),
                        total=len(examples),
                        disable=silent,
                    )
                )
```
from simpletransformers, even with using the with-gil-stack-rc-context

**Comment by cnuernber** [comment] 2020-04-08 22:14
That alone is a great find.  

In your example you are using lein exec and just running `(use '[ns])`.  This eliminates any possible threads around requiring variables, correct?

So, ruling out actually breaking things by accessing python from more than one thread (even in namespace definition functions like `def` is a large piece and I believe you have done that.

Googling for 'embedded multiprocessing python crash' gave a couple interesting results:
https://stackoverflow.com/questions/15636266/embedded-python-multiprocessing-not-working
https://stackoverflow.com/questions/24894682/python-multiprocessing-crash-in-subprocess

Why wouldn't this crash the system every time?  Why only sometimes?  I believe those issues above cause crashing every time.

What if you use multiprocessing alone without the rest of the example?

**Comment by behrica** [comment] 2020-04-08 22:43
The simpletransfomer projects has 2 issues open, which ,might relate to the case here:

https://github.com/ThilinaRajapakse/simpletransformers/issues/162
https://github.com/ThilinaRajapakse/simpletransformers/issues/225

**Comment by behrica** [comment] 2020-04-09 16:22
> That alone is a great find.
> 
I am wondering, if I want to embark into libpython-clj for deep learning.

What I have seen so far, is impressive, but this multiprocessor issue made me think again.

I an way I was lucky, because transformers has a configuration option to disable multiprocessor, and I could get it working.

What happens if not ?

Do I need to worry about each library if it "very deeply" uses some multiprocessor calls, which might not work as expected in libpython-clj.

Do you think this can be "fixed" in a way (so that then "arbitrary" python multiprocessor code in libpython-clj would work) ?  Or is this a fundamental problem of "embedded pyton" ?

**Comment by cnuernber** [comment] 2020-04-09 16:53
I don't really know the answers to that and I do not think anyone really does.  Specifically about the multiprocessor module in python it obviously overlaps poorly with both clojure's base set of functionality and some details about embedded python.  Definitely running python in an embedded mode changes some important variables.

We have used mxnet for facial rec a bit and haven't had many problems.  So it depends on your DL stack and how it interacts with libpython-clj.  The fallback is just to startup python from command line or from a docker container and process data alone with it.

What happens if not? - You use a network or command line wrapper.  Using require-python's `reload` facility can help develop these short scripts.

Do I need to worry about each library? - I think the majority of python libraries do in fact work fine.

Can this be fixed? - This is a productive question.  Most likely not but we haven't really given it a solid try.  The problem is fundamental; the C process state is different between a jvm process and a pure C process in many ways.  But there are a lot of things above that are unexplained; the main one is 'why doesn't this fail every time'.  I don't see forking processes to be something the jvm isn't ever going to support well mainly because it overrides a lot of signals and that is a deep C-level system call.

**Comment by cnuernber** [comment] 2021-03-05 15:05
@behrica - The next step of this would be to load your clojure via python's java plugin thus making python the host.  Then multiprocessing would work - there is [prior art here](https://github.com/clj-python/libpython-clj/issues/94).  Or we could try to make a native graal shared library which and load that with cython.  Either would be interesting next steps to alleviate this issue and allow easier embedding of clojure code into existing larger python systems.

**Comment by cnuernber** [comment] 2021-03-11 19:13
@behrica - There is now another option - you can [embed Clojure in Python](https://clj-python.github.io/libpython-clj/embedded.html) which allows the multithreading module to work as it allows forking of the process in a way that the multithreading module would expect.

That I think really is the best we can do at this time with this issue.

**Closed by cnuernber** 2021-03-11 19:13 UTC
